blank_issues_enabled: false
contact_links:
  - name: EspoCRM forum
    url: https://forum.espocrm.com/
    about: "Use our forum for help requests and questions not related to product development. We don't provide support on GitHub."
